---
title: "SDS291_GP_data_merge"
author: "Claire Kelly"
format: html
---

```{r}
library(tidyverse)
library (janitor)
```

```{r}
doctor_data <- read_csv("medical_doctor_data.csv")

mortality_data <- read_csv("mortality_data.csv")

pollution_data <- read_csv("PM25-air-pollution.csv")

income_data <- read_csv("country_incomelevel.csv", name_repair = make.names)
```


## Mortality Data (2019)

```{r}
mortality_data_edit <- mortality_data |> 
  filter(Period == 2019, 
         Dim1ValueCode == "BTSX", 
         IndicatorCode == "SDGAIRBOD",
         Dim2 == "Total") |>
  select(ParentLocationCode, 
         ParentLocation, 
         SpatialDimValueCode, 
         Location,
         FactValueNumeric,
         FactValueNumericHigh,
         FactValueNumericLow,
         Value)

```


## Doctor Data (2019)

```{r}
doctor_data_edit <- doctor_data |> 
  filter(Period == 2019) |>
  select(ParentLocationCode, 
         ParentLocation, 
         SpatialDimValueCode, 
         Location,
         FactValueNumeric, 
         Value)
```

## Pollution data (2017)
```{r}
pollution_data_edit <- pollution_data |>
  filter(Year == 2017)
```

## Income data (2019)
```{r}
income_data_edit <- income_data |>
  rename(IncomeGroup = Income.group, LendingCategory = Lending.category, GNI_per_capita = X2019) |>
  select(Country:Region, GNI_per_capita) |>
  mutate(GNI_per_capita = na_if(GNI_per_capita, "null"))
```


```{r}
WBcountry <- read_csv("WITSCountryProfile-Country_Indicator_ProductMetada-en.csv", name_repair = make.names)
```

```{r}
WBcountry_edit <- WBcountry |>
  select(Country.Name, Country.ISO3)
```

```{r}
income_data_edit <- income_data_edit |>
  inner_join(WBcountry_edit, by = c("Country" = "Country.Name"))
```

## Joining data

```{r}
merged_data <- mortality_data_edit |> 
  inner_join(doctor_data_edit, by = c("SpatialDimValueCode" = "SpatialDimValueCode")) |> 
  rename(ParentLocation = ParentLocation.x, 
         ParentLocationCode = ParentLocationCode.x,
         Location = Location.x,
         AvgMortalityRate = FactValueNumeric.x,
         LowMortalityRate = FactValueNumericLow,
         HighMoralityRate = FactValueNumericHigh,
         MortalityRate = Value.x,
         DoctorRate = Value.y) |>
  select(ParentLocation,
         ParentLocationCode,
         SpatialDimValueCode,
         Location,
         AvgMortalityRate,
         LowMortalityRate,
         HighMoralityRate,
         MortalityRate,
         DoctorRate)

merged_data <- merged_data |>
  inner_join(pollution_data_edit, by = c("SpatialDimValueCode" = "Code"))

merged_data <- merged_data |>
  inner_join(income_data_edit, by = c("SpatialDimValueCode" = "Country.ISO3"))
```


## Final 

```{r}
merged_data <- merged_data |>
  select(ParentLocation:DoctorRate, 
         `PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)`, 
         IncomeGroup, 
         GNI_per_capita) %>% 
  mutate(type = recode(IncomeGroup,
                    "Upper middle income" ="Middle Income",
                    "Lower middle income" ="Middle Income"))
```

## EDA

```{r}
ggplot (data= merged_data, mapping = aes (y = AvgMortalityRate, 
                                          x = `PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)` ))+ 
  geom_point()+
  geom_smooth (method = lm, se = FALSE, formula = y~x)
```

```{r}
ggplot (data= merged_data, mapping = aes (y = AvgMortalityRate, 
                                          x = DoctorRate))+ 
  geom_point()+
  geom_smooth (method = lm, se = FALSE, formula = y~x)
```
```{r}
ggplot (data= merged_data, mapping = aes (y = AvgMortalityRate, 
                                          x = `PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)`,
                                          color = IncomeGroup))+ 
  geom_point()+
  geom_smooth (method = lm, se = FALSE, formula = y~x)
```

```{r}
ggplot (data= merged_data, mapping = aes (y = AvgMortalityRate, 
                                          x = DoctorRate,
                                          color = IncomeGroup))+ 
  geom_point()+
  geom_smooth (method = lm, se = FALSE, formula = y~x)
```
